presentation/Store.Web/Models/SearchViewModel.cs
namespace Store.Web.Models
{
    public class SearchViewModel
    {
        public string query { get; set; }
    }
}

presentation/Store.Web/Controllers/DescController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Store.Web.App;

namespace Store.Web.Controllers
{
    public class DescController : Controller
    {
        // GET: DescController
        private readonly ProductService productservice;
        public DescController(ProductService productservice) {
            this.productservice=productservice;
        }

        public ActionResult Index(int id)
        {
            ProductModel product = productservice.GetById(id);
            return View(product);
        }

    }
}

presentation/Store.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.App;
using Store.Web.Models;

namespace Store.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly ProductService productService;
        public SearchController(ProductService productService)
        {       
            this.productService = productService;
        }
        
        [HttpPost]
        public IActionResult Index(string? query)
        {
            IReadOnlyCollection<ProductModel> products;
            products=productService.GetByQuery(query);
            return View(products);
        }
    }
}

presentation/Store.Web/Views/Search/Index.cshtml
@using Store.Web.App
@model IReadOnlyCollection<ProductModel>
@{
    
}

<div>
    @if (Model.Count== 0)
    {
        @:<div>По вашему запросу ничего не найдено.</div>
    }
     else
    {
     <div>По вашему запросу найдено @Model.Count товаров:</div>
        <table width="600" cellpadding="15" cellpadding="5">
            <tr>
                @{
                    int i = 0;
                    foreach(var model in @Model)
                    {
                        var product = model;
                        <td><div class="image-frame"><img src="@product.imgsrc" class="man_f" /></div><br /><div class="desc_text"> @Html.ActionLink(product.name, "Index", "Desc", new { id = product.id })</div></td>
                         @if (i%3==2)
                            {
                                @:<tr/>
                                @:<tr>
                            }
                        i += 1;

                    }
                }
        </tr>
        </table>
    }


</div>